// eslint-disable-next-line no-undef
define([], function() {
  return {
    PropertyPaneDescription: "Description",
    BasicGroupName: "Group Name",
    DescriptionFieldLabel: "Description Field",
    AppLocalEnvironmentSharePoint: "The app is running on your local environment as SharePoint web part",
    AppLocalEnvironmentTeams: "The app is running on your local environment as Microsoft Teams app",
    AppLocalEnvironmentOffice: "The app is running on your local environment in office.com",
    AppLocalEnvironmentOutlook: "The app is running on your local environment in Outlook",
    AppSharePointEnvironment: "The app is running on SharePoint page",
    AppTeamsTabEnvironment: "The app is running in Microsoft Teams",
    AppOfficeEnvironment: "The app is running in office.com",
    AppOutlookEnvironment: "The app is running in Outlook",
    UnknownEnvironment: "The app is running in an unknown environment",
    Description: "Settings",
    GeneralGroupName: "General",
    ToggleLabel: "One Element",
    ImageButtonLabel: "Select Background Image",
    ImageLabel: "Background Image",
    PageLabel: "Page Title",
    FirstGroupName: "First Item",
    FirstGroupDateLabel: "Select the date",
    FirstGroupUrlLabel: "Url",
    FirstGroupTitle: "Title",
    FirstGroupButtonLabel: "Select Image",
    FirstGroupImageLabel: "First Item Image",
    SecondGroupName: "Second Item",
    SecondGroupDateLabel: "Select the date",
    SecondGroupUrlLabel: "Url",
    SecondGroupTitle: "Title",
    SecondGroupButtonLabel: "Select Image",
    SecondGroupImageLabel: "Second Item Image",
    ThirdGroupName: "Third Item",
    ThirdGroupDateLabel: "Select the date",
    ThirdGroupUrlLabel: "Url",
    ThirdGroupTitle: "Title",
    ThirdGroupButtonLabel: "Select Image",
    ThirdGroupImageLabel: "Third Item Image",
    FourthGroupName: "Fourth Item",
    FourthGroupDateLabel: "Select the date",
    FourthGroupUrlLabel: "Url",
    FourthGroupTitle: "Title",
    FourthGroupButtonLabel: "Select Image",
    FourthGroupImageLabel: "Fourth Item Image",
    peoplePickerLabel: "Target Audience",
    colorPickerLabel: "Choose a color",
  }
});